theme: jekyll-theme-minimal

title: The Hybrid Systems Engineer
description: Real-world Microsoft hybrid infrastructure, identity, and automation engineering.

logo: 
show_downloads: false

github:
  is_project_page: false
